Add Check Volumes

diff --git a/bin/db-start b/bin/db-start
--- a/bin/db-start
+++ b/bin/db-start
@@ -2,6 +2,12 @@
 
 source ./bin/init-env
 
+docker volume ls | grep ${SERVICE_NAME}-db-data 1> /dev/null
+if [[ $? = 1 ]]; then
+  echo "Volume missing, please run ./bin/docker-setup"
+  exit 1
+fi
+
 function cmd() {
 
   array=()
